name: "Thundra Maven Test Instrumentation"
description: "Thundra Maven Test Instrumentation"
author: "Oguzhan Ozdemir <oguzhan.ozdemir@thundra.io>"
inputs:
  apikey:
    required: true
    description: "Thundra's API Key"
  project_id:
    required: true
    description: "Thundra's Test Project ID"
  command:
    required: false
    description: "Command to run your tests"
  instrumenter_version:
    required: false
    description: "Use a specific version of the Maven instrumentation script"
  agent_version:
    required: false
    description: "Use a specific version of the Thundra Agent"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "cloud-lightning"
  color: "yellow"
